"""change order

Revision ID: 3c1fcb8b0cc0
Revises: e3eda40c3d84
Create Date: 2021-02-21 12:45:19.512495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1fcb8b0cc0'
down_revision = 'e3eda40c3d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
