"""rename name to title

Revision ID: 0e227b56a647
Revises: 3c1fcb8b0cc0
Create Date: 2021-02-21 12:47:12.912166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e227b56a647'
down_revision = '3c1fcb8b0cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', sa.String(length=30), nullable=False))
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###
