"""add status enum

Revision ID: a570e2302197
Revises: 0e227b56a647
Create Date: 2021-02-21 12:54:45.056252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a570e2302197'
down_revision = '0e227b56a647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('account_status', sa.Enum('open', 'close', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'account_status')
    # ### end Alembic commands ###
