"""change column

Revision ID: e3eda40c3d84
Revises: e1376d6927c0
Create Date: 2021-02-21 12:43:05.385518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eda40c3d84'
down_revision = 'e1376d6927c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
