"""add status enum

Revision ID: 7ff80522ffdc
Revises: a570e2302197
Create Date: 2021-02-21 13:06:37.810881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff80522ffdc'
down_revision = 'a570e2302197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
