"""add status enum

Revision ID: 2d56ad262302
Revises: 7ff80522ffdc
Create Date: 2021-02-21 13:08:25.003051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d56ad262302'
down_revision = '7ff80522ffdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
