"""change column

Revision ID: e1376d6927c0
Revises: f3e578cf134d
Create Date: 2021-02-21 12:31:33.116102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1376d6927c0'
down_revision = 'f3e578cf134d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###
